name: CI - Marmitaria

on:
  push:
    branches:
      - master

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm ci

      - name: Executar testes
        run: npm test
      
      - name: fazer build
        run: npm run build