name: CI - Marmitaria

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: npm test

      - name: Fazer build
        run: npm run build

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem
        run: docker build -t ghcr.io/terabitssoftware/marmitaria-aluno01:latest .

      - name: Publicar imagem no GHCR
        run: docker push ghcr.io/terabitssoftware/marmitaria-aluno01:latest